apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: enrichment-dev

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: enrichment-api
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: HorizontalPodAutoscaler
      name: enrichment-api
    patch: |
      $patch: delete
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: enrichment-api

configMapGenerator:
  - name: enrichment-config
    behavior: merge
    literals:
      - LOG_LEVEL=DEBUG
      - DEFAULT_MAX_VARIATIONS=2
      - MAX_CONCURRENT_VARIATIONS=2

images:
  - name: ghcr.io/OWNER/domain-enrichment-api
    newTag: dev-latest
