replicaCount: 2

image:
  tag: "rc-latest"

ingress:
  enabled: true
  hosts:
    - host: enrichment-staging.example.com
      paths:
        - path: /api
          pathType: Prefix

config:
  LOG_LEVEL: "INFO"

pdb:
  enabled: true
  minAvailable: 1
