apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: enrichment-staging

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: enrichment-api
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2

configMapGenerator:
  - name: enrichment-config
    behavior: merge
    literals:
      - LOG_LEVEL=INFO

images:
  - name: ghcr.io/OWNER/domain-enrichment-api
    newTag: rc-latest
