apiVersion: v1
kind: ServiceAccount
metadata:
  name: enrichment-api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: enrichment-api
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: enrichment-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: enrichment-api
subjects:
  - kind: ServiceAccount
    name: enrichment-api
