"""
Convergence Loop Schemas — request/response types for multi-pass enrichment.

Defines ConvergeRequest, PassResult, ConvergeResponse, SchemaProposal,
and supporting types used by the convergence controller and API endpoints.

ROI 4: Adds inference_unlock_score to PassResult for telemetry.
"""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, Field

from .schemas import EnrichRequest

# ═══════════════════════════════════════════════════════════════════════════
# Convergence Request
# ═══════════════════════════════════════════════════════════════════════════


class ApprovalMode(StrEnum):
    """Schema proposal approval mode."""

    AUTO = "auto"  # Autonomous tier: auto-approve proposals
    HUMAN = "human"  # Discover tier: require human review


class ConvergeRequest(EnrichRequest):
    """
    Multi-pass convergence loop request.

    Extends EnrichRequest with convergence-specific parameters:
    - max_passes: Hard limit on iteration count
    - max_budget_tokens: Cost ceiling (Sonar tokens)
    - approval_mode: Schema proposal handling (auto/human)
    - convergence_threshold: Uncertainty target for termination
    """

    domain: str = Field(..., description="Domain identifier (e.g., 'plastics')")
    max_passes: int = Field(default=5, ge=1, le=10, description="Maximum convergence passes")
    max_budget_tokens: int = Field(default=50000, ge=1000, description="Token budget ceiling")
    approval_mode: ApprovalMode = Field(
        default=ApprovalMode.HUMAN, description="Schema proposal approval mode"
    )
    convergence_threshold: float = Field(
        default=2.0, ge=0.0, description="Uncertainty threshold for convergence"
    )


# ═══════════════════════════════════════════════════════════════════════════
# Pass Result
# ═══════════════════════════════════════════════════════════════════════════


class PassResult(BaseModel):
    """
    Results from a single convergence pass.

    Captures enriched fields, inferred fields, confidence deltas, uncertainty
    reduction, token cost, and timing. Used for telemetry and convergence analysis.

    ROI 4: Added inference_unlock_score and top_unlock_field for tracking
    inference-unlock-aware targeting effectiveness.
    """

    pass_number: int = Field(..., ge=1, description="Pass sequence number (1-indexed)")
    mode: Literal["discovery", "targeted", "verification"] = Field(
        ..., description="Enrichment mode for this pass"
    )
    fields_enriched: list[str] = Field(
        default_factory=list, description="Field names populated by enrichment"
    )
    fields_inferred: list[str] = Field(
        default_factory=list, description="Field names derived by inference rules"
    )
    field_confidences: dict[str, float] = Field(
        default_factory=dict,
        description="Per-field confidence scores after this pass (0.0-1.0)",
    )
    uncertainty_before: float = Field(..., ge=0.0, description="Uncertainty score at pass start")
    uncertainty_after: float = Field(..., ge=0.0, description="Uncertainty score at pass end")
    tokens_used: int = Field(..., ge=0, description="Sonar tokens consumed this pass")
    duration_ms: int = Field(..., ge=0, description="Pass execution time (milliseconds)")

    # ROI 4: Inference unlock targeting telemetry
    top_unlock_field: str | None = Field(
        default=None,
        description="Highest-priority field targeted (unlock-aware ranking)",
    )
    inference_unlock_score: float = Field(
        default=0.0,
        ge=0.0,
        description="Unlock score of top_unlock_field (downstream inference value)",
    )

    # Optional metadata
    kb_fragments_used: list[str] = Field(
        default_factory=list, description="KB fragment IDs injected this pass"
    )
    variation_count: int = Field(
        default=1, ge=1, le=5, description="Sonar variations used this pass"
    )


# ═══════════════════════════════════════════════════════════════════════════
# Schema Proposal
# ═══════════════════════════════════════════════════════════════════════════


class SchemaProposal(BaseModel):
    """
    Proposed field addition to domain schema.

    Generated by schema_discovery after convergence loop discovers new fields
    with sufficient fill rate and confidence across a batch.
    """

    field_name: str = Field(..., description="Proposed field name")
    field_type: str = Field(..., description="Proposed data type (string, float, bool, list, etc.)")
    source: Literal["enrichment", "inference"] = Field(..., description="How field was discovered")
    fill_rate: float = Field(
        ..., ge=0.0, le=1.0, description="Fraction of entities with this field populated"
    )
    avg_confidence: float = Field(
        ..., ge=0.0, le=1.0, description="Mean confidence across populated entities"
    )
    sample_values: list[Any] = Field(
        default_factory=list, description="Sample values from discovered entities"
    )
    proposed_gate: dict[str, Any] | None = Field(
        default=None, description="Optional gate definition if field enables matching"
    )
    proposed_scoring_dimension: dict[str, Any] | None = Field(
        default=None, description="Optional scoring dimension if field affects ranking"
    )


# ═══════════════════════════════════════════════════════════════════════════
# Convergence Response
# ═══════════════════════════════════════════════════════════════════════════


class ConvergenceReason(StrEnum):
    """Reason why convergence loop terminated."""

    THRESHOLD_MET = "threshold_met"  # Uncertainty below threshold
    BUDGET_EXHAUSTED = "budget_exhausted"  # Token budget depleted
    MAX_PASSES = "max_passes"  # Reached max_passes limit
    HUMAN_HOLD = "human_hold"  # Schema proposals require human approval
    ERROR = "error"  # Unrecoverable error occurred


class ConvergeResponse(BaseModel):
    """
    Multi-pass convergence loop response.

    Contains final enriched entity, per-pass telemetry, schema proposals,
    convergence reason, and cost summary.
    """

    entity_id: str = Field(..., description="Entity identifier")
    domain: str = Field(..., description="Domain identifier")
    passes: list[PassResult] = Field(
        default_factory=list, description="Per-pass results in sequence"
    )
    final_fields: dict[str, Any] = Field(
        default_factory=dict, description="Final entity state after convergence"
    )
    final_field_confidences: dict[str, float] = Field(
        default_factory=dict, description="Per-field confidence scores (final state)"
    )
    schema_proposals: list[SchemaProposal] = Field(
        default_factory=list,
        description="Discovered fields proposed for domain schema",
    )
    convergence_reason: ConvergenceReason = Field(..., description="Why loop terminated")
    total_tokens: int = Field(..., ge=0, description="Total Sonar tokens consumed")
    total_cost_usd: float = Field(..., ge=0.0, description="Total enrichment cost (USD)")
    domain_yaml_version_before: str | None = Field(
        default=None, description="Domain YAML version at loop start"
    )
    domain_yaml_version_after: str | None = Field(
        default=None, description="Domain YAML version at loop end (if updated)"
    )
    duration_ms: int = Field(..., ge=0, description="Total loop execution time (ms)")
    created_at: datetime = Field(default_factory=datetime.utcnow, description="Response timestamp")


# ═══════════════════════════════════════════════════════════════════════════
# Batch Convergence
# ═══════════════════════════════════════════════════════════════════════════


class BatchConvergeRequest(BaseModel):
    """
    Batch convergence request for multiple entities.

    Supports enrichment profile selection for targeted batch processing
    (e.g., nightly-stale, high-null, failed-match entities).
    """

    entities: list[dict[str, Any]] = Field(..., description="List of entities to converge")
    domain: str = Field(..., description="Domain identifier")
    profile_name: str | None = Field(
        default=None,
        description="Enrichment profile name (e.g., 'nightly-stale', 'high-null')",
    )
    max_budget_tokens: int = Field(
        default=100000, ge=1000, description="Total token budget for batch"
    )
    convergence_threshold: float = Field(
        default=2.0, ge=0.0, description="Per-entity uncertainty threshold"
    )


class BatchConvergeResponse(BaseModel):
    """
    Batch convergence response.

    Contains per-entity convergence results plus aggregate statistics.
    """

    results: list[ConvergeResponse] = Field(
        default_factory=list, description="Per-entity convergence results"
    )
    total_entities: int = Field(..., ge=0, description="Total entities processed")
    succeeded: int = Field(..., ge=0, description="Entities converged successfully")
    failed: int = Field(..., ge=0, description="Entities failed to converge")
    total_tokens: int = Field(..., ge=0, description="Total Sonar tokens consumed")
    total_cost_usd: float = Field(..., ge=0.0, description="Total batch cost (USD)")
    avg_passes_per_entity: float = Field(..., ge=0.0, description="Mean passes per entity")
    duration_ms: int = Field(..., ge=0, description="Total batch execution time (ms)")


# ═══════════════════════════════════════════════════════════════════════════
# Pass Context (Internal Use)
# ═══════════════════════════════════════════════════════════════════════════


class PassContext(BaseModel):
    """
    Internal context passed between convergence loop iterations.

    Not exposed in API — used by convergence_controller.py.
    """

    pass_number: int
    budget_remaining: int
    previous_uncertainty: float
    previous_passes: list[PassResult] = Field(default_factory=list)
