"""
Convergence Loop Schemas — request/response types for multi-pass enrichment.

Defines ConvergeRequest, PassResult, ConvergeResponse, SchemaProposal,
and supporting types used by the convergence controller and API endpoints.

ROI 4: Adds inference_unlock_score to PassResult for telemetry.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from enum import StrEnum
from typing import Any
from uuid import uuid4

from pydantic import BaseModel, Field, field_validator

# Enums


class ConvergenceMode(StrEnum):
    """Enrichment mode for convergence pass."""

    DISCOVERY = "discovery"
    TARGETED = "targeted"
    VERIFICATION = "verification"


class ApprovalMode(StrEnum):
    """Schema proposal approval mode."""

    AUTO = "auto"  # Autonomous tier: auto-approve proposals
    HUMAN = "human"  # Discover tier: require human review


class ConvergenceReason(StrEnum):
    """Reason why convergence loop terminated."""

    THRESHOLD_MET = "threshold_met"  # Uncertainty below threshold
    BUDGET_EXHAUSTED = "budget_exhausted"  # Token budget depleted
    MAX_PASSES = "max_passes"  # Reached max_passes limit
    HUMAN_HOLD = "human_hold"  # Schema proposals require human approval
    DIMINISHING_RETURNS = "diminishing_returns"  # ROI below threshold
    FAILED = "failed"  # Unrecoverable error occurred


class SchemaProposalSource(StrEnum):
    """Source of schema proposal."""

    ENRICHMENT = "enrichment"
    INFERENCE = "inference"


class ApprovalDecision(StrEnum):
    """Schema proposal approval decision."""

    APPROVED = "approved"
    REJECTED = "rejected"
    PENDING = "pending"


# ═══════════════════════════════════════════════════════════════════════════
# Cost Summary
# ═══════════════════════════════════════════════════════════════════════════


class CostSummary(BaseModel):
    """Cost tracking for convergence run."""

    total_tokens: int = Field(default=0, ge=0)
    total_cost_usd: float = Field(default=0.0, ge=0.0)
    cost_per_field: float = Field(default=0.0, ge=0.0)
    budget_utilization_pct: float = Field(default=0.0, ge=0.0)
    tokens_per_pass: list[int] = Field(default_factory=list)

    @field_validator("total_cost_usd", "cost_per_field", "budget_utilization_pct", mode="after")
    @classmethod
    def round_to_6_decimals(cls, v: float) -> float:
        return round(v, 6)


# ═══════════════════════════════════════════════════════════════════════════
# Schema Proposal
# ═══════════════════════════════════════════════════════════════════════════


class SchemaProposal(BaseModel):
    """
    Proposed field addition to domain schema.

    Generated by schema_discovery after convergence loop discovers new fields
    with sufficient fill rate and confidence across a batch.
    """

    field_name: str = Field(..., description="Proposed field name")
    field_type: str = Field(default="string", description="Proposed data type")
    source: SchemaProposalSource = Field(
        default=SchemaProposalSource.ENRICHMENT, description="How field was discovered"
    )
    fill_rate: float = Field(default=0.0, ge=0.0, le=1.0, description="Fraction populated")
    avg_confidence: float = Field(default=0.0, ge=0.0, le=1.0, description="Mean confidence")
    sample_values: list[Any] = Field(default_factory=list, max_length=10)
    proposed_gate: str | None = Field(default=None)
    proposed_scoring_dimension: str | None = Field(default=None)


# ═══════════════════════════════════════════════════════════════════════════
# Pass Result
# ═══════════════════════════════════════════════════════════════════════════


class PassResult(BaseModel):
    """
    Results from a single convergence pass.

    Captures enriched fields, inferred fields, confidence deltas, uncertainty
    reduction, token cost, and timing.
    """

    pass_number: int = Field(..., ge=1, description="Pass sequence number (1-indexed)")
    mode: ConvergenceMode = Field(default=ConvergenceMode.DISCOVERY)
    fields_enriched: list[str] = Field(default_factory=list)
    fields_inferred: list[str] = Field(default_factory=list)
    field_confidences: dict[str, float] = Field(default_factory=dict)
    uncertainty_before: float = Field(default=0.0, ge=0.0)
    uncertainty_after: float = Field(default=0.0, ge=0.0)
    tokens_used: int = Field(default=0, ge=0)
    duration_ms: int = Field(default=0, ge=0)
    rules_fired: list[str] = Field(default_factory=list)
    error: str | None = Field(default=None)

    # ROI 4: Inference unlock targeting telemetry
    top_unlock_field: str | None = Field(default=None)
    inference_unlock_score: float = Field(default=0.0, ge=0.0)

    # Optional metadata
    kb_fragments_used: list[str] = Field(default_factory=list)
    variation_count: int = Field(default=1, ge=1, le=5)

    @property
    def uncertainty_delta(self) -> float:
        """Uncertainty reduction this pass."""
        return self.uncertainty_before - self.uncertainty_after

    @property
    def fields_gained(self) -> int:
        """Total fields populated this pass."""
        return len(self.fields_enriched) + len(self.fields_inferred)


# ═══════════════════════════════════════════════════════════════════════════
# Convergence Request
# ═══════════════════════════════════════════════════════════════════════════


class ConvergeRequest(BaseModel):
    """
    Multi-pass convergence loop request.

    Extends EnrichRequest with convergence-specific parameters.
    """

    entity: dict[str, Any] = Field(..., min_length=1)
    object_type: str = Field(...)
    objective: str = Field(...)
    domain: str | None = Field(default=None)
    run_id: str = Field(default_factory=lambda: str(uuid4()))
    idempotency_key: str | None = Field(default=None)
    max_passes: int = Field(default=5, ge=1, le=20)
    max_budget_tokens: int = Field(default=50000, ge=1000)
    approval_mode: ApprovalMode = Field(default=ApprovalMode.HUMAN)
    convergence_threshold: float = Field(default=2.0, ge=0.0, le=10.0)
    consensus_threshold: float = Field(default=0.65, ge=0.0, le=1.0)
    max_variations: int = Field(default=3, ge=1, le=10)
    target_schema: dict[str, Any] | str | None = Field(default=None)

    @field_validator("target_schema", mode="before")
    @classmethod
    def parse_schema_string(cls, v: Any) -> dict[str, Any] | None:
        if isinstance(v, str):
            try:
                return json.loads(v)
            except json.JSONDecodeError:
                return None
        return v


# ═══════════════════════════════════════════════════════════════════════════
# Convergence Response
# ═══════════════════════════════════════════════════════════════════════════


class ConvergeResponse(BaseModel):
    """
    Multi-pass convergence loop response.

    Contains final enriched entity, per-pass telemetry, schema proposals,
    convergence reason, and cost summary.
    """

    entity_id: str = Field(default="")
    domain: str = Field(default="")
    state: str = Field(default="running")
    passes: list[PassResult] = Field(default_factory=list)
    final_fields: dict[str, Any] = Field(default_factory=dict)
    final_field_confidences: dict[str, float] = Field(default_factory=dict)
    schema_proposals: list[SchemaProposal] = Field(default_factory=list)
    convergence_reason: ConvergenceReason = Field(default=ConvergenceReason.MAX_PASSES)
    total_tokens: int = Field(default=0, ge=0)
    total_cost_usd: float = Field(default=0.0, ge=0.0)
    domain_yaml_version_before: str | None = Field(default=None)
    domain_yaml_version_after: str | None = Field(default=None)
    kb_content_hash: str | None = Field(default=None)
    duration_ms: int = Field(default=0, ge=0)
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    completed_at: datetime | None = Field(default=None)

    @property
    def total_passes(self) -> int:
        return len(self.passes)

    @property
    def total_fields_discovered(self) -> int:
        return len(self.final_fields)

    @property
    def is_converged(self) -> bool:
        return self.convergence_reason == ConvergenceReason.THRESHOLD_MET


# ═══════════════════════════════════════════════════════════════════════════
# Batch Convergence
# ═══════════════════════════════════════════════════════════════════════════


class BatchConvergeRequest(BaseModel):
    """Batch convergence request for multiple entities."""

    entities: list[ConvergeRequest] = Field(..., max_length=50)
    profile_name: str | None = Field(default=None)
    max_budget_tokens: int = Field(default=100000, ge=1000)
    convergence_threshold: float = Field(default=2.0, ge=0.0)


class BatchConvergeResponse(BaseModel):
    """Batch convergence response."""

    results: list[ConvergeResponse] = Field(default_factory=list)
    total: int = Field(default=0, ge=0)
    succeeded: int = Field(default=0, ge=0)
    failed: int = Field(default=0, ge=0)
    total_tokens: int = Field(default=0, ge=0)
    total_cost_usd: float = Field(default=0.0, ge=0.0)
    avg_passes_per_entity: float = Field(default=0.0, ge=0.0)
    duration_ms: int = Field(default=0, ge=0)
    schema_proposal_set: list[SchemaProposal] | None = Field(default=None)


# ═══════════════════════════════════════════════════════════════════════════
# Convergence Report (Telemetry)
# ═══════════════════════════════════════════════════════════════════════════


class ConvergenceReport(BaseModel):
    """Telemetry report for convergence analysis."""

    run_id: str = Field(...)
    passes_completed: int = Field(default=0, ge=0)
    confidence_trajectory: list[float] = Field(default_factory=list)
    uncertainty_trajectory: list[float] = Field(default_factory=list)
    tokens_per_pass: list[int] = Field(default_factory=list)
    cost_per_pass_usd: list[float] = Field(default_factory=list)
    roi_per_pass: list[float] = Field(default_factory=list)


# ═══════════════════════════════════════════════════════════════════════════
# Pass Context (Internal Use)
# ═══════════════════════════════════════════════════════════════════════════


class PassContext(BaseModel):
    """Internal context passed between convergence loop iterations."""

    pass_number: int
    budget_remaining: int
    previous_uncertainty: float
    previous_passes: list[PassResult] = Field(default_factory=list)
