"""Request / response schemas for the enrichment-inference convergence loop.

These types extend the single-pass ``EnrichRequest`` / ``EnrichResponse``
contracts in ``schemas.py`` with multi-pass orchestration primitives:
convergence requests, per-pass snapshots, schema proposals, and the
aggregate convergence response.

Every convergence-layer file imports from here.  The dependency graph is:
    schemas.py → field_confidence.py → loop_schemas.py → everything else.

Exports:
    ConvergenceMode     – Enum: discovery | targeted | verification.
    ApprovalMode        – Enum: auto | human.
    ConvergenceReason   – Enum: why the loop terminated.
    SchemaProposalSource – Enum: enrichment | inference.
    SchemaProposal      – A proposed field addition to the domain YAML.
    PassResult          – Snapshot of a single convergence pass.
    ConvergeRequest     – Initiates a multi-pass convergence loop.
    ConvergeResponse    – Full result of a completed (or halted) loop.
    BatchConvergeRequest / BatchConvergeResponse – Batch wrappers.
    ApprovalDecision    – Human approve/reject per proposed field.
    CostSummary         – Token + USD cost breakdown.
    ConvergenceReport   – Pass-over-pass telemetry for ROI proof.
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from uuid import uuid4

from pydantic import BaseModel, Field, field_validator

from .field_confidence import FieldConfidenceMap, FieldSource


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class ConvergenceMode(str, Enum):
    """What kind of enrichment pass to run."""
    DISCOVERY = "discovery"
    TARGETED = "targeted"
    VERIFICATION = "verification"


class ApprovalMode(str, Enum):
    """Schema-proposal approval policy."""
    AUTO = "auto"
    HUMAN = "human"


class ConvergenceReason(str, Enum):
    """Why the convergence loop terminated."""
    THRESHOLD_MET = "threshold_met"
    BUDGET_EXHAUSTED = "budget_exhausted"
    MAX_PASSES = "max_passes"
    HUMAN_HOLD = "human_hold"
    DIMINISHING_RETURNS = "diminishing_returns"
    FAILED = "failed"


class SchemaProposalSource(str, Enum):
    """How a proposed field was discovered."""
    ENRICHMENT = "enrichment"
    INFERENCE = "inference"


# ---------------------------------------------------------------------------
# Cost tracking (lightweight, embedded in responses)
# ---------------------------------------------------------------------------

class CostSummary(BaseModel):
    """Cumulative token + cost breakdown across all passes."""

    total_tokens: int = 0
    total_cost_usd: float = 0.0
    tokens_per_pass: List[int] = Field(default_factory=list)
    cost_per_field: float = 0.0
    budget_utilization_pct: float = 0.0

    @field_validator("total_cost_usd", "cost_per_field", "budget_utilization_pct", mode="before")
    @classmethod
    def round_cost(cls, v: Any) -> float:
        return round(float(v), 6)


# ---------------------------------------------------------------------------
# Schema proposals
# ---------------------------------------------------------------------------

class SchemaProposal(BaseModel):
    """A proposed addition to the customer's domain YAML.

    Generated by the schema proposer after batch convergence reveals
    a new field with sufficient fill-rate and confidence across entities.
    """

    field_name: str
    field_type: str = "string"
    source: SchemaProposalSource = SchemaProposalSource.ENRICHMENT
    fill_rate: float = Field(default=0.0, ge=0.0, le=1.0)
    avg_confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    sample_values: List[Any] = Field(default_factory=list, max_length=10)
    proposed_gate: Optional[str] = None
    proposed_scoring_dimension: Optional[str] = None
    description: Optional[str] = None


class SchemaProposalSet(BaseModel):
    """Aggregated schema proposals from a batch convergence run."""

    proposed_fields: List[SchemaProposal] = Field(default_factory=list)
    proposed_gates: List[str] = Field(default_factory=list)
    proposed_scoring_dimensions: List[str] = Field(default_factory=list)
    yaml_diff: str = ""
    version_bump: str = ""


class ApprovalDecision(BaseModel):
    """Human approve/reject for a single proposed field (Discover tier)."""

    field_name: str
    approved: bool = False
    reviewer: Optional[str] = None
    reason: Optional[str] = None


# ---------------------------------------------------------------------------
# Per-pass snapshot
# ---------------------------------------------------------------------------

class PassResult(BaseModel):
    """Immutable snapshot of one convergence pass.

    Captured after each enrichment + inference cycle.  The convergence
    controller appends these to ``ConvergeResponse.passes``.
    """

    pass_number: int = Field(ge=1)
    mode: ConvergenceMode = ConvergenceMode.DISCOVERY
    fields_enriched: List[str] = Field(default_factory=list)
    fields_inferred: List[str] = Field(default_factory=list)
    field_confidences: FieldConfidenceMap = Field(default_factory=FieldConfidenceMap)
    uncertainty_before: float = 0.0
    uncertainty_after: float = 0.0
    tokens_used: int = 0
    duration_ms: int = 0
    rules_fired: List[str] = Field(default_factory=list)
    error: Optional[str] = None

    @property
    def uncertainty_delta(self) -> float:
        return round(self.uncertainty_before - self.uncertainty_after, 4)

    @property
    def fields_gained(self) -> int:
        return len(self.fields_enriched) + len(self.fields_inferred)


# ---------------------------------------------------------------------------
# Convergence request
# ---------------------------------------------------------------------------

class ConvergeRequest(BaseModel):
    """Initiates a multi-pass enrichment-inference convergence loop.

    Extends the single-pass ``EnrichRequest`` contract with loop controls:
    max passes, token budget, approval mode, convergence threshold.
    """

    entity: Dict[str, Any] = Field(..., min_length=1)
    object_type: str
    objective: str
    domain: str = ""
    kb_context: Optional[str] = None
    schema: Optional[Dict[str, str]] = None

    # Loop controls
    max_passes: int = Field(default=5, ge=1, le=20)
    max_budget_tokens: int = Field(default=50_000, ge=1_000)
    convergence_threshold: float = Field(default=2.0, ge=0.0, le=10.0)
    consensus_threshold: float = Field(default=0.65, ge=0.0, le=1.0)
    max_variations: int = Field(default=5, ge=1, le=10)
    approval_mode: ApprovalMode = ApprovalMode.AUTO

    # Provenance
    idempotency_key: Optional[str] = None
    run_id: str = Field(default_factory=lambda: str(uuid4()))

    @field_validator("schema", mode="before")
    @classmethod
    def parse_schema_string(cls, v: Any) -> Optional[Dict[str, str]]:
        if isinstance(v, str):
            import json
            try:
                parsed = json.loads(v)
                return parsed if isinstance(parsed, dict) else None
            except json.JSONDecodeError:
                return None
        return v


# ---------------------------------------------------------------------------
# Convergence response
# ---------------------------------------------------------------------------

class ConvergeResponse(BaseModel):
    """Full result of a convergence loop (or a snapshot if still running)."""

    run_id: str = Field(default_factory=lambda: str(uuid4()))
    entity_id: Optional[str] = None
    domain: str = ""
    state: str = "running"

    # Pass history
    passes: List[PassResult] = Field(default_factory=list)

    # Final outputs
    final_fields: Dict[str, Any] = Field(default_factory=dict)
    final_field_confidences: FieldConfidenceMap = Field(default_factory=FieldConfidenceMap)
    schema_proposals: List[SchemaProposal] = Field(default_factory=list)

    # Termination
    convergence_reason: Optional[ConvergenceReason] = None
    total_tokens: int = 0
    total_cost_usd: float = 0.0
    cost_summary: Optional[CostSummary] = None

    # Domain YAML version tracking
    domain_yaml_version_before: Optional[str] = None
    domain_yaml_version_after: Optional[str] = None

    # Timing
    total_duration_ms: int = 0
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    completed_at: Optional[datetime] = None

    # Provenance
    inference_version: str = "v2.2.0"
    kb_content_hash: Optional[str] = None
    kb_files_consulted: List[str] = Field(default_factory=list)

    @property
    def total_passes(self) -> int:
        return len(self.passes)

    @property
    def total_fields_discovered(self) -> int:
        return len(self.final_fields)

    @property
    def is_converged(self) -> bool:
        return self.convergence_reason == ConvergenceReason.THRESHOLD_MET


# ---------------------------------------------------------------------------
# Convergence telemetry report
# ---------------------------------------------------------------------------

class ConvergenceReport(BaseModel):
    """Pass-over-pass telemetry proving diminishing-cost convergence.

    This is the data that justifies the upsell:
    'Pass 1 cost $0.25 → 12 fields.  Pass 2 cost $0.08 → 6 more.
     Pass 3 cost $0.03 → confirmed 3.  Total: $0.36 for 21 fields at 0.91.'
    """

    run_id: str
    passes_completed: int = 0
    fields_per_pass: List[int] = Field(default_factory=list)
    confidence_trajectory: List[float] = Field(default_factory=list)
    uncertainty_trajectory: List[float] = Field(default_factory=list)
    tokens_per_pass: List[int] = Field(default_factory=list)
    cost_per_pass_usd: List[float] = Field(default_factory=list)
    roi_per_pass: List[float] = Field(default_factory=list)
    convergence_reason: Optional[ConvergenceReason] = None
    total_cost_usd: float = 0.0
    final_confidence: float = 0.0


# ---------------------------------------------------------------------------
# Batch wrappers
# ---------------------------------------------------------------------------

class BatchConvergeRequest(BaseModel):
    """Batch convergence for multiple entities with shared budget."""

    entities: List[ConvergeRequest] = Field(..., max_length=50)
    profile_name: Optional[str] = None
    max_budget_tokens: int = Field(default=250_000, ge=1_000)


class BatchConvergeResponse(BaseModel):
    results: List[ConvergeResponse] = Field(default_factory=list)
    total: int = 0
    succeeded: int = 0
    failed: int = 0
    total_tokens: int = 0
    total_cost_usd: float = 0.0
    total_duration_ms: int = 0
    schema_proposal_set: Optional[SchemaProposalSet] = None
